import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';

import 'lenis/dist/lenis.css';
import './styles/reset.css';
import './styles/tokens.css';
import './styles/global.css';

import { displayFont, monoFont } from './fonts/fonts';
import { MotionProvider } from '@/lib/motion/MotionProvider';
import { Loader } from '@/components/chrome/Loader';
import { Navbar } from '@/components/chrome/Navbar';
import { Footer } from '@/components/chrome/Footer';
import { ContactPanel } from '@/components/chrome/ContactPanel';
import { Hero3D } from '@/components/hero/Hero3D';
import { SITE } from '@/lib/content/site';

/**
 * `app/opengraph-image.png`, `app/icon.svg` and `app/apple-icon.png` are picked
 * up by convention — Next wires them into <head> without being named here. They
 * are generated by `npm run brand:assets` from the same ratios as
 * components/brand/ApertureMark.tsx. See 50-brand-and-3d.md §4.
 *
 * `metadataBase` is what turns those conventional files into the absolute URLs
 * OG scrapers require. Without it Next warns and emits relative paths, which
 * silently produces a card that renders nowhere.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.name,
    template: `%s — ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  openGraph: {
    type: 'website',
    siteName: SITE.name,
    title: SITE.name,
    description: SITE.description,
    url: '/',
    locale: 'en',
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE.name,
    description: SITE.description,
  },
};

export const viewport: Viewport = {
  themeColor: '#212121',
  colorScheme: 'dark',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${displayFont.variable} ${monoFont.variable}`}>
      <body>
        <MotionProvider>
          <a className="skip-link" href="#main">
            Skip to content
          </a>
          {/* Chrome lives outside <main> so it survives route changes — the
              loader in particular has to persist across the navigation it is
              covering, and Hero3D so its WebGL context is created exactly once
              per session rather than once per navigation. */}
          <Loader />
          <Navbar />
          <Hero3D />
          <main id="main">{children}</main>
          <Footer />
          <ContactPanel />
        </MotionProvider>
      </body>
    </html>
  );
}
