/**
 * Generates every raster brand asset from one source of truth.
 *
 *   npm run brand:assets
 *
 * Outputs (all committed):
 *   app/icon.svg              64×64   the favicon, scalable — covers the 32 case
 *   app/apple-icon.png        180×180 the iOS home-screen tile
 *   public/icon-512.png       512×512 referenced by app/manifest.ts
 *   app/opengraph-image.png   1200×630 glyph + wordmark on --black
 *
 * docs/spec/50-brand-and-3d.md §4 names 32 / 180 / 512 for the favicon and
 * 1200×630 for the OG card.
 *
 * WHY A SCRIPT AND NOT next/og. `ImageResponse` cannot load a woff2, and
 * General Sans ships from Fontshare as a variable woff2 only — an OG card set in
 * a substitute face would misrepresent the wordmark, which is the one thing the
 * card exists to show. Playwright is already a devDependency for the verify
 * harness, it renders the real face, and the output is a static file with zero
 * runtime cost. The trade is that the assets are generated at author time and
 * committed rather than rendered on request; they change about as often as the
 * brand does.
 *
 * The aperture below is the same four ratios as components/brand/ApertureMark.tsx.
 * If those ever diverge, this comment is the bug report.
 */
import { chromium } from 'playwright';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/* ── the mark, from the spec's ratios ─────────────────────────────────────── */
const SIZE = 48;
const C = SIZE / 2;
const RING = SIZE / 12; // stroke weight: 1/12 of the diameter
const R = (SIZE - RING) / 2; // centreline radius
const INNER = R - RING / 2; // the ring's inner edge
const TICK = R / 6; // tick length: 1/6 of the radius
const TICK_STROKE = RING / 2; // half the ring's weight — I-009
const OFF = 8; // degrees off-radial

const round = (n) => +n.toFixed(4);

/** The mark's inner geometry, unpositioned. `stroke` is a literal colour. */
function apertureGroup(stroke) {
  const ticks = Array.from({ length: 6 }, (_, i) => {
    const t = `rotate(${i * 60} ${C} ${C}) rotate(${OFF} ${C} ${round(C - INNER)})`;
    return `      <line x1="${C}" y1="${round(C - INNER)}" x2="${C}" y2="${round(C - INNER + TICK)}" transform="${t}"/>`;
  }).join('\n');
  return [
    `  <g fill="none" stroke="${stroke}">`,
    `    <circle cx="${C}" cy="${C}" r="${R}" stroke-width="${RING}"/>`,
    `    <g stroke-width="${TICK_STROKE}">`,
    ticks,
    `    </g>`,
    `  </g>`,
  ].join('\n');
}

const SVG_HEADER = `<!--
  GENERATED by scripts/brand-assets.mjs — run \`npm run brand:assets\`. Do not
  hand-edit; edit the script.

  The No Filter mark as the favicon. docs/spec/50-brand-and-3d.md §1 and §4. Its
  geometry is the same four ratios as components/brand/ApertureMark.tsx, so the
  favicon and the on-page glyph cannot drift apart.

  Two differences from the component, both forced by the medium. The colours are
  literal, because a standalone SVG has nothing to inherit \`currentColor\` from.
  And it sits on a filled --black tile rather than on transparency: a white mark
  on a transparent ground disappears against a light browser tab and a black one
  disappears against a dark tab, so the tile is what makes it survive both.

  The mark occupies 48 of the 64-unit tile — a 12.5% safe area on each side,
  which keeps it clear of the rounding some platforms apply.
-->`;

/** A standalone tile: the mark on a filled --black ground, with a safe area. */
function tileSvg(px, header = false) {
  const TILE = 64;
  const pad = (TILE - SIZE) / 2;
  return [
    ...(header ? [SVG_HEADER] : []),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TILE} ${TILE}" width="${px}" height="${px}">`,
    `  <rect width="${TILE}" height="${TILE}" fill="#212121"/>`,
    `  <g transform="translate(${pad} ${pad})">`,
    apertureGroup('#efefef')
      .split('\n')
      .map((l) => '  ' + l)
      .join('\n'),
    `  </g>`,
    `</svg>`,
  ].join('\n');
}

/* ── rendering ────────────────────────────────────────────────────────────── */

async function shoot(page, html, width, height, out) {
  await page.setViewportSize({ width, height });
  await page.setContent(html, { waitUntil: 'load' });
  await page.evaluate(() => document.fonts.ready);
  const buf = await page.screenshot({ omitBackground: false });
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, buf);
  console.log(`  ${out.replace(ROOT, '.')}  ${width}×${height}`);
}

const shell = (body, css = '') => `<!doctype html><html><head><meta charset="utf-8">
<style>
  html,body{margin:0;padding:0;background:#212121;}
  ${css}
</style></head><body>${body}</body></html>`;

async function main() {
  console.log('▸ brand assets');

  // The real display face, inlined — the OG card exists to show the wordmark and
  // a fallback would defeat it.
  const gs = await readFile(resolve(ROOT, 'app/fonts/GeneralSans-Variable.woff2'));
  const face = `@font-face{font-family:'General Sans';font-weight:200 700;font-display:block;
    src:url(data:font/woff2;base64,${gs.toString('base64')}) format('woff2');}`;

  // 1. the scalable favicon
  await writeFile(resolve(ROOT, 'app/icon.svg'), tileSvg(64, true) + '\n');
  console.log('  ./app/icon.svg  64×64');

  const browser = await chromium.launch();
  const page = await browser.newPage({ deviceScaleFactor: 1 });

  // 2 & 3. the raster tiles
  for (const [px, out] of [
    [180, resolve(ROOT, 'app/apple-icon.png')],
    [512, resolve(ROOT, 'public/icon-512.png')],
  ]) {
    await shoot(page, shell(tileSvg(px)), px, px, out);
  }

  // 4. the OG card — glyph and wordmark on --black, left-aligned on a
  //    12-column-ish rhythm rather than centred, which is how the site is set.
  const og = shell(
    `<div class="card">
       <div class="mark">${tileSvg(120).replace(/<rect[^>]*\/>/, '')}</div>
       <div class="wm"><span>NO</span><span class="gap"></span><span>FiLTER</span></div>
       <div class="line"></div>
       <div class="tag">A studio for work that does not need softening.</div>
     </div>`,
    `${face}
     .card{width:1200px;height:630px;background:#212121;box-sizing:border-box;
       padding:96px;display:flex;flex-direction:column;justify-content:flex-end;gap:40px;}
     .mark{width:120px;height:120px;position:absolute;top:96px;left:96px;}
     .mark svg{width:120px;height:120px;display:block;}
     .wm{font-family:'General Sans',sans-serif;font-weight:400;letter-spacing:-0.02em;
       line-height:1;color:#efefef;font-size:168px;display:flex;align-items:baseline;}
     .wm .gap{display:inline-block;width:0.22em;}
     .line{height:1px;background:rgba(255,255,255,.3);}
     .tag{font-family:'General Sans',sans-serif;font-weight:400;font-size:30px;
       line-height:1.3;color:#737373;letter-spacing:-0.01em;}`
  );
  await shoot(page, og, 1200, 630, resolve(ROOT, 'app/opengraph-image.png'));

  await browser.close();
  console.log('✓ brand assets written');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
